// Splitstream tracking + variant assignment for Vite / React.
//
// Generated by Splitstream — do not edit manually.
//
// Three exports:
//
//   initSplitstream()        — call from src/main.tsx before React mounts.
//                              Resolves the variant cookie, loads PostHog,
//                              tags pageview + conversion events with
//                              workspace / experiment / variant.
//
//   useSplitstreamVariant()  — React hook used by variant PRs to swap copy
//                              between A and B inline. Returns "A" or "B".
//                              Components import this directly; the install
//                              PR doesn't wire it up — variant PRs do.
//
// The cookie is assigned on the first visit (50/50 split) and persisted
// for 30 days. Bots get "A" so crawler traffic doesn't skew the test.

import { useEffect, useState } from "react";

const COOKIE_VARIANT = "splitstream_variant";

function readCookie(name: string): string | null {
  if (typeof document === "undefined") return null;
  const m = document.cookie.match(new RegExp("(?:^|; )" + name + "=([^;]+)"));
  return m ? decodeURIComponent(m[1]) : null;
}

function writeCookie(name: string, value: string, days: number): void {
  if (typeof document === "undefined") return;
  document.cookie = name + "=" + value + "; max-age=" + days * 86400 + "; path=/; samesite=lax";
}

/**
 * Internal force-mode helper. Returns the requested variant when the
 * page URL carries `?splitstream_force=A` or `?splitstream_force=B`,
 * else null. Same semantics as the App Router branch — internal-only
 * (Browserless screenshots, dashboard preview links, drift-check
 * renders). NEVER advertised to customers.
 */
function readForcedVariant(): "A" | "B" | null {
  if (typeof window === "undefined") return null;
  try {
    const params = new URLSearchParams(window.location.search);
    const f = params.get("splitstream_force");
    return f === "A" || f === "B" ? f : null;
  } catch (e) {
    return null;
  }
}

/**
 * Resolve the variant. Order of precedence:
 *   1. `?splitstream_force=A|B` URL param (internal automation only).
 *      Never writes the cookie, so a force-mode URL shared by accident
 *      doesn't pin a real visitor to one variant.
 *   2. Bot UA → always "A".
 *   3. Existing splitstream_variant cookie.
 *   4. Fresh 50/50 roll, persisted.
 *
 * Safe to call from initSplitstream and from the hook's effect — both
 * go through this same path so they can't disagree.
 */
function resolveVariant(): "A" | "B" {
  const forced = readForcedVariant();
  if (forced) return forced;
  if (typeof navigator !== "undefined" && /(bot|crawl|spider|slurp)/i.test(navigator.userAgent || "")) {
    return "A";
  }
  const existing = readCookie(COOKIE_VARIANT);
  if (existing === "A" || existing === "B") return existing;
  const fresh: "A" | "B" = Math.random() < 0.5 ? "A" : "B";
  writeCookie(COOKIE_VARIANT, fresh, 30);
  return fresh;
}

export function initSplitstream(): void {
  if (typeof window === "undefined") return;
  if ((window as unknown as { __splitstreamPosthogLoaded?: boolean }).__splitstreamPosthogLoaded) return;
  (window as unknown as { __splitstreamPosthogLoaded?: boolean }).__splitstreamPosthogLoaded = true;

  const variant = resolveVariant();

  // Force-mode short-circuit (Browserless screenshots, dashboard
  // preview links, drift-check renders). See the App Router branch
  // for the full rationale — same five suppressions: no /api/track,
  // no session cookie, no PostHog, no signal eval, no SPA observer.
  if (readForcedVariant() !== null) {
    (window as unknown as { splitstream?: unknown }).splitstream = {
      track: () => {},
      pageview: () => {},
      identify: () => {},
    };
    return;
  }

  const experimentId = readCookie("splitstream_experiment");

  // First-party conversion tracking runs UNCONDITIONALLY — independent
  // of PostHog (ad-blockers commonly kill posthog-js).

      // ── Splitstream first-party tracking core ──────────────────────
      // Page-arrival conversion tracking. Never blocks the page; all
      // failures are swallowed. Conversions are attributed server-side.
      const __SS_BASE = "https://splitstream.ai";
      const __SS_WS = "23810c00-1ea2-423b-bd56-9b56a081015f";
      const __SS_SIGNALS: Array<{ goalId: string; type: string; selector: string | null; key: string | null }> = [];
      const __SS_SESSION_COOKIE = "splitstream_session";
      const __SS_SESSION_TTL_MIN = 30;

      const __ssReadCookie = (n: string): string | null => {
        try {
          const m = document.cookie.match(
            new RegExp("(?:^|; )" + n + "=([^;]+)"),
          );
          return m ? decodeURIComponent(m[1]) : null;
        } catch (e) {
          return null;
        }
      };
      const __ssWriteCookie = (n: string, v: string, mins: number): void => {
        try {
          document.cookie =
            n +
            "=" +
            encodeURIComponent(v) +
            "; max-age=" +
            mins * 60 +
            "; path=/; samesite=lax";
        } catch (e) {
          /* cookie write blocked — tracking degrades, page unaffected */
        }
      };
      const __ssUuid = (): string => {
        try {
          if (
            typeof crypto !== "undefined" &&
            typeof crypto.randomUUID === "function"
          ) {
            return crypto.randomUUID();
          }
        } catch (e) {
          /* fall through */
        }
        return "ss-" + Date.now().toString(36) + "-" +
          Math.random().toString(36).slice(2, 10);
      };

      // Session: reuse the cookie if present (and refresh its sliding
      // TTL); otherwise mint a new id. previouslySeen drives
      // heuristic-mode detection server-side.
      const __ssPriorSession = __ssReadCookie(__SS_SESSION_COOKIE);
      const __ssSessionId = __ssPriorSession || __ssUuid();
      const __ssPreviouslySeen = !!__ssPriorSession;
      __ssWriteCookie(__SS_SESSION_COOKIE, __ssSessionId, __SS_SESSION_TTL_MIN);

      const __ssEvalSignals = (): Record<string, boolean> => {
        const out: Record<string, boolean> = {};
        for (const sig of __SS_SIGNALS) {
          try {
            if (sig.type === "css_selector" && sig.selector) {
              out[sig.goalId] = !!document.querySelector(sig.selector);
            } else if (sig.type === "localStorage_key" && sig.key) {
              out[sig.goalId] =
                window.localStorage.getItem(sig.key) !== null;
            }
          } catch (e) {
            out[sig.goalId] = false;
          }
        }
        return out;
      };

      // Pageview dedupe — keyed on path+search AND a short time
      // window. The four nav hooks (pushState, replaceState, popstate,
      // MutationObserver+poll) can each fire for one navigation event;
      // a 200 ms collapse window swallows the duplicates while leaving
      // a deliberate revisit (back / forward / same-URL nav) reportable.
      let __ssLastKey = "";
      let __ssLastSentAt = 0;
      const __SS_DEDUP_MS = 200;
      const __ssSend = (path: string, body: Record<string, unknown>): void => {
        try {
          const json = JSON.stringify(body);
          // text/plain keeps this a CORS "simple request": no preflight,
          // works from any customer origin, never blocks navigation.
          const url = __SS_BASE + path;
          if (
            typeof navigator !== "undefined" &&
            typeof navigator.sendBeacon === "function"
          ) {
            const blob = new Blob([json], { type: "text/plain" });
            if (navigator.sendBeacon(url, blob)) return;
          }
          fetch(url, {
            method: "POST",
            body: json,
            headers: { "content-type": "text/plain" },
            keepalive: true,
            mode: "cors",
            credentials: "omit",
          }).catch(() => {});
        } catch (e) {
          /* never surface tracking errors to the customer's users */
        }
      };

      const __ssPageview = (manual?: boolean): void => {
        try {
          // Refresh the sliding session TTL on every pageview.
          __ssWriteCookie(
            __SS_SESSION_COOKIE,
            __ssSessionId,
            __SS_SESSION_TTL_MIN,
          );
          const key =
            window.location.pathname + window.location.search;
          const now = Date.now();
          // Time-windowed dedupe. `manual` (window.splitstream.pageview())
          // bypasses entirely — the customer asked for the send.
          if (
            !manual &&
            key === __ssLastKey &&
            now - __ssLastSentAt < __SS_DEDUP_MS
          ) {
            return;
          }
          __ssLastKey = key;
          __ssLastSentAt = now;
          __ssSend("/api/track", {
            workspace_id: __SS_WS,
            session_id: __ssSessionId,
            pathname: window.location.pathname,
            search: window.location.search,
            variant_cookie_value: __ssReadCookie("splitstream_variant"),
            signals: __ssEvalSignals(),
            previously_seen: __ssPreviouslySeen,
          });
        } catch (e) {
          /* swallow */
        }
      };

      // Public API. identify() is accepted but unused in v1.
      (window as unknown as { splitstream?: unknown }).splitstream = {
        track: (eventName: string, properties?: Record<string, unknown>) => {
          __ssSend("/api/track/event", {
            workspace_id: __SS_WS,
            session_id: __ssSessionId,
            event_name: eventName,
            properties: properties || {},
            variant_cookie_value: __ssReadCookie("splitstream_variant"),
            pathname: window.location.pathname,
          });
        },
        identify: (_userId: string, _traits?: Record<string, unknown>) => {
          /* reserved for v2 */
        },
        pageview: () => __ssPageview(true),
      };

      // SPA navigation hooking. History API monkey-patch + popstate
      // covers Next.js & most routers; the MutationObserver + location
      // poll is the framework-agnostic safety net (React Router,
      // Remix, anything that swaps the DOM without a History event we
      // caught).
      try {
        const __ssHist = window.history;
        const __ssWrap = (fnName: "pushState" | "replaceState") => {
          const orig = __ssHist[fnName];
          __ssHist[fnName] = function (this: History, ...args: unknown[]) {
            const r = (orig as (...a: unknown[]) => unknown).apply(this, args);
            setTimeout(() => __ssPageview(), 0);
            return r;
          } as History[typeof fnName];
        };
        __ssWrap("pushState");
        __ssWrap("replaceState");
        window.addEventListener("popstate", () => __ssPageview(), {
          passive: true,
        });
      } catch (e) {
        /* history hook failed — observer fallback below still works */
      }
      try {
        let __ssObsLast =
          window.location.pathname + window.location.search;
        const __ssCheck = () => {
          const k = window.location.pathname + window.location.search;
          if (k !== __ssObsLast) {
            __ssObsLast = k;
            __ssPageview();
          }
        };
        new MutationObserver(__ssCheck).observe(document, {
          subtree: true,
          childList: true,
        });
        window.setInterval(__ssCheck, 1000);
      } catch (e) {
        /* observer unsupported — initial pageview still fires */
      }

      // Initial pageview.
      __ssPageview();

  // PostHog loaded ONLY for guardrail metrics now.
  const s = document.createElement("script");
  s.src = "https://events.splitstream.ai/static/array.js";
  s.async = true;
  s.onload = () => {
    const w = window as unknown as {
      posthog?: {
        init: (k: string, o: Record<string, unknown>) => void;
        register: (p: Record<string, unknown>) => void;
        capture: (e: string) => void;
      };
    };
    if (!w.posthog) return;
    w.posthog.init("phc_oFqJPhGKQyXNzSt6J9XLPFHNK6NtdMuLnUNGUuAZxLub", {
      api_host: "https://events.splitstream.ai",
      capture_pageview: true,
      person_profiles: "identified_only",
    });
    const props: Record<string, string> = {
      splitstream_workspace_id: "23810c00-1ea2-423b-bd56-9b56a081015f",
      splitstream_variant: variant,
    };
    if (experimentId) props.splitstream_experiment_id = experimentId;
    w.posthog.register(props);
  };
  document.head.appendChild(s);
}

/**
 * Hook used by variant PRs to swap copy.
 *
 * Force-mode (?splitstream_force=A|B): the lazy initial state reads
 * the URL param synchronously on mount so Browserless screenshots
 * (which always carry the force param) see the right variant on the
 * first render. Without this, framer-motion's initial:opacity=0 +
 * delayed animations could paint the A copy after useEffect's
 * setVariant("B") commits, and the screenshot would capture A even
 * though the URL forced B.
 *
 * For real visitors (no force param): initial render returns "A",
 * useEffect runs resolveVariant() and honours the cookie. B-cookie
 * users see one frame of A then swap (~16 ms) — acceptable for a
 * CRO test and avoids hydration mismatches in SSR setups.
 */
export function useSplitstreamVariant(): "A" | "B" {
  const [variant, setVariant] = useState<"A" | "B">(() => {
    if (typeof window === "undefined") return "A";
    const forced = readForcedVariant();
    return forced ?? "A";
  });
  useEffect(() => {
    const v = resolveVariant();
    if (v !== variant) setVariant(v);
  }, []);
  return variant;
}
